"""
ngspice 网表生成器 V2.0 — process-aware · ngspice 45 兼容

从 DesignState 生成 SPICE 网表。

双 pass 架构：
  Pass 1 (AC):  .ac + .meas ac → simulator 提取 gain/GBW/PM
  Pass 2 (DC):  .dc + .control → simulator 提取 power + 工作点

网表包含两种分析，simulator 负责分拆执行。
"""
from __future__ import annotations

import math
from typing import Dict, List, Optional
from pathlib import Path
from schemas.design_state import DesignState


class NetlistGenerator:
    """ngspice 网表生成器（双 pass 兼容）。"""

    def __init__(self, state: DesignState):
        self.state = state
        self._proc = state.process

    def generate(self, include_header: bool = True) -> str:
        lines = []
        if include_header:
            lines.append(f"* {self.state.design_name}")
            lines.append(f"* Auto-generated by objective_ir NetlistGenerator V2.0")
            lines.append(f"* Process: {self._proc.process_name or 'PTM 130nm'}")
            lines.append(f"* Topology: {self.state.topology.name}")
            lines.append("")

        lines.extend(self._gen_library())
        lines.append(".options savecurrents")
        lines.append("")
        lines.extend(self._gen_devices())
        lines.extend(self._gen_passives())
        lines.extend(self._gen_supplies())
        lines.extend(self._gen_bias())
        lines.extend(self._gen_stimuli())
        lines.extend(self._gen_load())
        lines.extend(self._gen_analyses())
        lines.extend(self._gen_measures())
        lines.append(".end")
        return "\n".join(lines)

    # ── Library ──

    def _resolve_model_path(self, model_name: str) -> Path:
        model_path = Path(model_name)
        if not model_path.is_absolute():
            candidate = Path(__file__).parent.parent / model_name
            if candidate.exists():
                model_path = candidate.resolve()
            elif model_path.exists():
                model_path = model_path.resolve()
        return model_path

    def _gen_library(self) -> List[str]:
        model_name = self._proc.model_lib or "ptm_130.lib"
        model_path = self._resolve_model_path(model_name)
        corner = getattr(self._proc, "model_corner", "") or ""
        osdi_libs = getattr(self._proc, "osdi_libs", []) or []
        lines = []
        if osdi_libs:
            lines.append("* OSDI models are loaded by simulator/ngspice.py via local .spiceinit")
            for osdi in osdi_libs:
                lines.append(f"* .osdi {self._resolve_model_path(osdi)}")
        if corner:
            lines.append(f'.lib "{model_path}" {corner}')
        else:
            lines.append(f'.include "{model_path}"')
        lines.extend([f".temp {self.state.simulation.temperature}", ""])
        return lines

    # ── Engineering formatting ──

    @staticmethod
    def _eng(val_si: float, grid_si: float) -> str:
        """SPICE 工程后缀：grid 精度决定有效位数，自动选 u/n/p。"""
        grid_um = grid_si * 1e6
        decimals = max(0, -int(round(math.log10(grid_um)))) if grid_um > 0 else 0
        um = val_si * 1e6
        nm = val_si * 1e9
        if um >= 1:
            return f"{um:.{decimals}f}u"
        elif nm >= 1:
            return f"{nm:.0f}n"
        else:
            return f"{val_si * 1e12:.0f}p"

    # ── Devices ──

    def _gen_devices(self) -> List[str]:
        W_grid = getattr(self._proc, "W_precision", 10e-9)
        L_grid = getattr(self._proc, "L_precision", 1e-9)
        lines = ["* -- Devices --"]
        for dev in self.state.topology.devices:
            ts = self.state.transistors.get(dev.id)
            if ts is None:
                continue
            conn = dev.connections
            d = conn.get("drain", "0")
            g = conn.get("gate", "0")
            s = conn.get("source", "0")
            b = conn.get("body", "0")
            W = ts.parameters.W if ts.parameters.W > 0 else 1e-6
            L = ts.parameters.L if ts.parameters.L > 0 else 1.3e-7
            model = dev.model or "nmos"
            if getattr(self._proc, "device_style", "mos") == "subckt":
                lines.append(f"X{dev.id} {d} {g} {s} {b} {model} W={self._eng(W, W_grid)} L={self._eng(L, L_grid)}")
            else:
                lines.append(f"M{dev.id} {d} {g} {s} {b} {model} W={self._eng(W, W_grid)} L={self._eng(L, L_grid)}")
        lines.append("")
        return lines

    def _get_global_param(self, name: str, default: Optional[float] = None) -> Optional[float]:
        params = getattr(self.state, "global_parameters", {}) or {}
        if name in params:
            return params[name]
        for dv in self.state.design_variables:
            if not dv.device and dv.variable == name:
                if dv.initial is not None:
                    return dv.initial
                return 0.5 * (dv.range.min + dv.range.max)
        return default

    def _fmt_si(self, val: float, suffix: str) -> str:
        if suffix == "F":
            if val >= 1e-9:
                return f"{val*1e9:.4g}n"
            if val >= 1e-12:
                return f"{val*1e12:.4g}p"
            return f"{val*1e15:.4g}f"
        if suffix == "Ohm":
            if val >= 1e6:
                return f"{val/1e6:.4g}Meg"
            if val >= 1e3:
                return f"{val/1e3:.4g}k"
            return f"{val:.4g}"
        return f"{val:.6g}"

    def _gen_passives(self) -> List[str]:
        """Generate compensation components driven by global variables."""
        cc = self._get_global_param("Cc")
        if cc is None or cc <= 0:
            return []

        out = None
        for p in self.state.topology.ports:
            if p.direction == "output":
                out = p.id
                break
        if out is None:
            out = "vout"

        comp_node = None
        for dev in self.state.topology.devices:
            if dev.role == "second_stage_gain":
                comp_node = dev.connections.get("gate")
                break
        if not comp_node:
            return []

        rz = self._get_global_param("Rz", 0.0) or 0.0
        lines = ["* -- Compensation --"]
        if rz > 1e-9:
            mid = "ncc"
            lines.append(f"Rz {comp_node} {mid} {self._fmt_si(rz, 'Ohm')}")
            lines.append(f"Cc {mid} {out} {self._fmt_si(cc, 'F')}")
        else:
            lines.append(f"Cc {comp_node} {out} {self._fmt_si(cc, 'F')}")
        lines.append("")
        return lines

    # ── Supplies / Bias / Stimuli / Load ──

    def _gen_supplies(self) -> List[str]:
        vdd = self.state.simulation.supply.get("vdd", 1.2)
        vss = self.state.simulation.supply.get("vss", 0.0)
        lines = ["* -- Supplies --", f"Vdd vdd 0 DC {vdd}"]
        if vss != 0:
            lines.append(f"Vss 0 vss DC {vss}")
        lines.append("")
        return lines

    def _gen_bias(self) -> List[str]:
        lines = ["* -- Bias --"]
        vdd = self.state.simulation.supply.get("vdd", 1.2)
        fallback = getattr(self.state.simulation, "bias_voltage", None)
        if fallback is None or fallback <= 0:
            fallback = vdd * 0.5
        handled_ports = set()

        for dev in self.state.topology.devices:
            if dev.role != "tail_bias_mirror":
                continue
            gate = dev.connections.get("gate", "")
            drain = dev.connections.get("drain", "")
            if not gate or gate != drain:
                continue
            ts = self.state.transistors.get(dev.id)
            iref = self._get_global_param(
                "I_tail",
                ts.parameters.id if ts and ts.parameters.id > 0 else 10e-6,
            )
            lines.append("* Tail bias mirror reference current")
            lines.append(f"Iref_tail vdd {gate} DC {self._fmt_si(float(iref), 'A')}")
            handled_ports.add(gate)
            break

        params = getattr(self.state, "global_parameters", {}) or {}
        if not handled_ports and float(params.get("tail_current_mirror_bias", 0.0) or 0.0) > 0.5:
            for dev in self.state.topology.devices:
                if dev.role != "tail_current_source" or dev.type != "nmos":
                    continue
                gate = dev.connections.get("gate", "")
                source = dev.connections.get("source", "0")
                body = dev.connections.get("body", source)
                if not gate:
                    continue
                ts = self.state.transistors.get(dev.id)
                W = ts.parameters.W if ts and ts.parameters.W > 0 else self._proc.min_W
                L = ts.parameters.L if ts and ts.parameters.L > 0 else self._proc.min_L
                iref = self._get_global_param(
                    "I_tail",
                    ts.parameters.id if ts and ts.parameters.id > 0 else 10e-6,
                )
                model = dev.model or self._proc.nmos_model or "nmos"
                lines.append("* Diode-connected NMOS mirror for tail bias")
                lines.append(f"Iref_tail vdd {gate} DC {self._fmt_si(float(iref), 'A')}")
                if getattr(self._proc, "device_style", "mos") == "subckt":
                    lines.append(
                        f"XBIAS{dev.id} {gate} {gate} {source} {body} {model} "
                        f"W={self._eng(W, self._proc.W_precision)} "
                        f"L={self._eng(L, self._proc.L_precision)}"
                    )
                else:
                    lines.append(
                        f"MBIAS{dev.id} {gate} {gate} {source} {body} {model} "
                        f"W={self._eng(W, self._proc.W_precision)} "
                        f"L={self._eng(L, self._proc.L_precision)}"
                    )
                handled_ports.add(gate)
                break

        for port in self.state.topology.ports:
            if port.direction != "bias":
                continue
            if port.id in handled_ports:
                continue
            vbias_v = fallback
            for dev in self.state.topology.devices:
                if dev.connections.get("gate") != port.id:
                    continue
                ts = self.state.transistors.get(dev.id)
                if ts and ts.parameters.vgs > 0:
                    if dev.type == "pmos":
                        vbias_v = vdd - ts.parameters.vgs
                    else:
                        vbias_v = ts.parameters.vgs
                break
            lines.append(f"V{port.id} {port.id} 0 DC {vbias_v:.4f}")

        if len(lines) == 1:
            return []
        lines.append("")
        return lines

    def _gen_stimuli(self) -> List[str]:
        vdd = self.state.simulation.supply.get("vdd", 1.2)
        vcm = vdd * 0.5
        inputs = [p for p in self.state.topology.ports if p.direction == "input"]
        lines = ["* -- Stimuli --"]
        if len(inputs) >= 2:
            lines.append(f"* Common-mode = {vcm:.2f}V, diff AC=0.5")
            lines.append(f"Vinp {inputs[0].id} 0 DC {vcm} AC 0.5")
            lines.append(f"Vinn {inputs[1].id} 0 DC {vcm} AC -0.5")
        elif len(inputs) == 1:
            lines.append(f"Vin {inputs[0].id} 0 DC {vcm} AC 1")
        lines.append("")
        return lines

    def _gen_load(self) -> List[str]:
        cl = self.state.simulation.cload
        if cl and cl > 0:
            outs = [p for p in self.state.topology.ports if p.direction == "output"]
            if outs:
                cl_ff = cl * 1e15
                return ["* -- Load --", f"Cload {outs[0].id} 0 {cl_ff:.1f}f", ""]
        return []

    # ── Analyses ──

    def _gen_analyses(self) -> List[str]:
        lines = ["* -- Analyses --"]
        vcm = self.state.simulation.supply.get("vdd", 1.2) * 0.5
        lines.append(f".dc Vinp {vcm:.3f} {vcm:.3f} 0.001")
        sim = self.state.simulation
        if "ac" in sim.analyses:
            lines.append(f".ac dec {sim.ac_points} {sim.ac_start} {sim.ac_stop}")
        lines.append("")
        return lines

    # ── Measures (L3 evaluations 驱动 .meas 生成) ──

    def _gen_measures(self) -> List[str]:
        """
        根据 L3 evaluations 生成 .meas 行。
        每个 Evaluation 映射到相应的 .meas 语句。
        """
        lines = ["* -- Measures --"]

        # 确定输出节点
        out = None
        for p in self.state.topology.ports:
            if p.direction == "output":
                out = p.id
                break
        if out is None:
            out = "vout"

        vdd = self.state.simulation.supply.get("vdd", 1.2)

        # 优先使用 L3 evaluations，否则 fallback 到 targets
        ev_list = self.state.evaluations if self.state.evaluations else []

        if ev_list:
            for ev in ev_list:
                probe = ev.probe or out
                if ev.meas_formula:
                    # 自定义 .meas 公式
                    lines.append(f".meas ac {ev.name} {ev.meas_formula}")
                elif ev.type == "ac_gain":
                    lines.append(f".meas ac {ev.name}_db max vdb({probe})")
                elif ev.type == "ugbw":
                    lines.append(f".meas ac {ev.name} when vdb({probe})=0")
                elif ev.type == "phase_margin":
                    lines.append(f".meas ac {ev.name} find vp({probe}) when vdb({probe})=0")
                elif ev.type == "dc_power":
                    lines.append(f".meas dc {ev.name} MAX par('{vdd}*abs(i(Vdd))')")
                elif ev.type == "cmrr":
                    lines.append(f"* .meas ac {ev.name} ... ; CMRR measurement TBD (unsupported)")
                elif ev.type == "psrr":
                    lines.append(f"* .meas ac {ev.name} ... ; PSRR measurement TBD (unsupported)")
                elif ev.type == "operating_region":
                    lines.append(f"* {ev.name}: operating region check via print all")
                else:
                    lines.append(f"* .meas {ev.name}: unknown type '{ev.type}' — skipped")
        else:
            # Fallback: 从 targets 推断 .meas
            targets = self.state.targets
            if "dc_gain" in targets:
                lines.append(f".meas ac dc_gain_db max vdb({out})")
            if "unity_gain_bandwidth" in targets:
                lines.append(f".meas ac ugbw when vdb({out})=0")
            if "phase_margin" in targets:
                lines.append(f".meas ac pm find vp({out}) when vdb({out})=0")
            if "power" in targets:
                lines.append(f".meas dc total_power MAX par('{vdd}*abs(i(Vdd))')")

        lines.append("")
        return lines

    # ── Save ──

    def save(self, path: str) -> str:
        content = self.generate()
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path


def generate_netlist(state: DesignState, output_path: Optional[str] = None) -> str:
    gen = NetlistGenerator(state)
    netlist = gen.generate()
    if output_path:
        gen.save(output_path)
    return netlist
