"""AnalogRF-IR internal documentation."""
from __future__ import annotations

import math
from typing import Dict, List, Optional
from pathlib import Path
from asir.profiles import select_circuit_profile
from layout.realization import LayoutRealization, realize_transistor_layout
from schemas.design_state import DesignState


class NetlistGenerator:
    """AnalogRF-IR internal documentation."""

    def __init__(self, state: DesignState):
        self.state = state
        self._proc = state.process
        self._profile = select_circuit_profile(state)

    def generate(self, include_header: bool = True) -> str:
        lines = []
        if include_header:
            lines.append(f"* {self.state.design_name}")
            lines.append("* Auto-generated by AnalogRF-IR v0.1 NetlistGenerator")
            lines.append(f"* Process: {self._proc.process_name or 'PTM 130nm'}")
            lines.append(f"* Topology: {self.state.topology.name}")
            lines.append(f"* VDSAT_headroom_factor: {getattr(self._proc, 'VDSAT_headroom_factor', 1.0):.6g}")
            lines.append("")

        lines.extend(self._gen_library())
        lines.append(".options savecurrents")
        lines.append("")
        lines.extend(self._gen_devices())
        lines.extend(self._gen_passives())
        lines.extend(self._gen_supplies())
        lines.extend(self._gen_bias())
        lines.extend(self._gen_stimuli())
        lines.extend(self._gen_load())
        lines.extend(self._gen_analyses())
        lines.extend(self._gen_measures())
        lines.append(".end")
        return "\n".join(lines)

    # Library

    def _resolve_model_path(self, model_name: str) -> Path:
        model_path = Path(model_name)
        if not model_path.is_absolute():
            candidate = Path(__file__).parent.parent / model_name
            if candidate.exists():
                model_path = candidate.resolve()
            elif model_path.exists():
                model_path = model_path.resolve()
        return model_path

    def _gen_library(self) -> List[str]:
        model_name = self._proc.model_lib or "ptm_130.lib"
        model_path = self._resolve_model_path(model_name)
        corner = getattr(self._proc, "model_corner", "") or ""
        osdi_libs = getattr(self._proc, "osdi_libs", []) or []
        lines = []
        if osdi_libs:
            lines.append("* OSDI models are loaded by simulator/ngspice.py via local .spiceinit")
            for osdi in osdi_libs:
                lines.append(f"* .osdi {self._resolve_model_path(osdi)}")
        if corner:
            lines.append(f'.lib "{model_path}" {corner}')
        else:
            lines.append(f'.include "{model_path}"')
        lines.extend([f".temp {self.state.simulation.temperature}", ""])
        return lines

    # Engineering formatting

    @staticmethod
    def _eng(val_si: float, grid_si: float) -> str:
        """AnalogRF-IR internal documentation."""
        grid_um = grid_si * 1e6
        decimals = max(0, -int(round(math.log10(grid_um)))) if grid_um > 0 else 0
        um = val_si * 1e6
        nm = val_si * 1e9
        if um >= 1:
            return f"{um:.{decimals}f}u"
        elif nm >= 1:
            return f"{nm:.0f}n"
        else:
            return f"{val_si * 1e12:.0f}p"

    # Devices

    def _gen_devices(self) -> List[str]:
        W_grid = getattr(self._proc, "W_precision", 10e-9)
        L_grid = getattr(self._proc, "L_precision", 1e-9)
        lines = ["* -- Devices --"]
        for dev in self.state.topology.devices:
            ts = self.state.transistors.get(dev.id)
            if ts is None:
                continue
            conn = dev.connections
            d = conn.get("drain", "0")
            g = conn.get("gate", "0")
            s = conn.get("source", "0")
            b = conn.get("body", "0")
            model = dev.model or "nmos"
            layout = realize_transistor_layout(self.state, dev.id)
            self._record_layout_realization(dev.id, layout)
            if layout.folded or layout.segmented:
                lines.append(
                    f"* layout {dev.id}: W_eff={self._eng(layout.effective_W, W_grid)} "
                    f"L_eff={self._eng(layout.effective_L, L_grid)} -> "
                    f"fingers={layout.fingers} parallel={layout.parallel} series={layout.series} "
                    f"W_finger={self._eng(layout.finger_W, W_grid)} "
                    f"L_segment={self._eng(layout.segment_L, L_grid)}"
                )
            lines.extend(self._gen_realized_mos(dev.id, d, g, s, b, model, layout))
        lines.append("")
        return lines

    def _record_layout_realization(self, device_id: str, layout: LayoutRealization) -> None:
        params = self.state.transistors[device_id].parameters
        params.layout_fingers = layout.fingers
        params.layout_parallel = layout.parallel
        params.layout_series = layout.series
        params.layout_finger_W = layout.finger_W
        params.layout_instance_W = layout.instance_W
        params.layout_segment_L = layout.segment_L

    def _gen_realized_mos(
        self,
        device_id: str,
        drain: str,
        gate: str,
        source: str,
        body: str,
        model: str,
        layout: LayoutRealization,
    ) -> List[str]:
        lines: List[str] = []
        for idx in range(layout.series):
            seg_drain = drain if idx == 0 else f"{device_id}_ser{idx}"
            seg_source = source if idx == layout.series - 1 else f"{device_id}_ser{idx + 1}"
            suffix = "" if idx == 0 else f"_S{idx + 1}"
            lines.append(
                self._mos_instance_line(
                    f"{device_id}{suffix}",
                    seg_drain,
                    gate,
                    seg_source,
                    body,
                    model,
                    layout,
                )
            )
        return lines

    def _mos_instance_line(
        self,
        instance_id: str,
        drain: str,
        gate: str,
        source: str,
        body: str,
        model: str,
        layout: LayoutRealization,
    ) -> str:
        W_grid = getattr(self._proc, "W_precision", 10e-9)
        L_grid = getattr(self._proc, "L_precision", 1e-9)
        if getattr(self._proc, "device_style", "mos") == "subckt":
            extras = []
            if layout.fingers > 1:
                extras.append(f"ng={layout.fingers}")
            if layout.parallel > 1:
                extras.append(f"m={layout.parallel}")
            extra_text = (" " + " ".join(extras)) if extras else ""
            return (
                f"X{instance_id} {drain} {gate} {source} {body} {model} "
                f"W={self._eng(layout.instance_W, W_grid)} "
                f"L={self._eng(layout.segment_L, L_grid)}{extra_text}"
            )
        multiplier = layout.fingers * layout.parallel
        extra_text = f" m={multiplier}" if multiplier > 1 else ""
        return (
            f"M{instance_id} {drain} {gate} {source} {body} {model} "
            f"W={self._eng(layout.finger_W, W_grid)} "
            f"L={self._eng(layout.segment_L, L_grid)}{extra_text}"
        )

    def _get_global_param(self, name: str, default: Optional[float] = None) -> Optional[float]:
        params = getattr(self.state, "global_parameters", {}) or {}
        if name in params:
            return params[name]
        for dv in self.state.design_variables:
            if not dv.device and dv.variable == name:
                if dv.initial is not None:
                    return dv.initial
                return 0.5 * (dv.range.min + dv.range.max)
        return default

    def _get_explicit_bias_voltage(self, port_id: str) -> Optional[float]:
        for key in (port_id, f"V{port_id}", f"{port_id}_voltage"):
            value = self._get_global_param(key)
            if value is not None:
                return float(value)
        return None

    def _is_comparator(self) -> bool:
        return self._profile.name == "comparator"

    def _fmt_si(self, val: float, suffix: str) -> str:
        if suffix == "F":
            if val >= 1e-9:
                return f"{val*1e9:.4g}n"
            if val >= 1e-12:
                return f"{val*1e12:.4g}p"
            return f"{val*1e15:.4g}f"
        if suffix == "Ohm":
            if val >= 1e6:
                return f"{val/1e6:.4g}Meg"
            if val >= 1e3:
                return f"{val/1e3:.4g}k"
            return f"{val:.4g}"
        return f"{val:.6g}"

    def _gen_passives(self) -> List[str]:
        """Generate compensation components driven by global variables."""
        cc = self._get_global_param("Cc")
        if cc is None or cc <= 0:
            return []

        out = None
        for p in self.state.topology.ports:
            if p.direction == "output":
                out = p.id
                break
        if out is None:
            out = "vout"

        comp_node = None
        for dev in self.state.topology.devices:
            if dev.role == "second_stage_gain":
                comp_node = dev.connections.get("gate")
                break
        if not comp_node:
            return []

        rz = self._get_global_param("Rz", 0.0) or 0.0
        lines = ["* -- Compensation --"]
        if rz > 1e-9:
            mid = "ncc"
            lines.append(f"Rz {comp_node} {mid} {self._fmt_si(rz, 'Ohm')}")
            lines.append(f"Cc {mid} {out} {self._fmt_si(cc, 'F')}")
        else:
            lines.append(f"Cc {comp_node} {out} {self._fmt_si(cc, 'F')}")
        lines.append("")
        return lines

    # Supplies, bias, stimuli, and load

    def _gen_supplies(self) -> List[str]:
        vdd = self.state.simulation.supply.get("vdd", 1.2)
        vss = self.state.simulation.supply.get("vss", 0.0)
        lines = ["* -- Supplies --", f"Vdd vdd 0 DC {vdd}"]
        if vss != 0:
            lines.append(f"Vss 0 vss DC {vss}")
        lines.append("")
        return lines

    def _gen_bias(self) -> List[str]:
        lines = ["* -- Bias --"]
        vdd = self.state.simulation.supply.get("vdd", 1.2)
        fallback = getattr(self.state.simulation, "bias_voltage", None)
        if fallback is None or fallback <= 0:
            fallback = vdd * 0.5
        handled_ports = set()

        bias_mirror_specs = {
            "tail_bias_mirror": ("I_tail", "Iref_tail", 10e-6),
            "output_bias_mirror": ("I_stage2", "Iref_stage2", 20e-6),
        }
        for dev in self.state.topology.devices:
            if dev.role not in bias_mirror_specs:
                continue
            gate = dev.connections.get("gate", "")
            drain = dev.connections.get("drain", "")
            if not gate or gate != drain:
                continue
            ts = self.state.transistors.get(dev.id)
            current_name, source_name, default_current = bias_mirror_specs[dev.role]
            iref = self._get_global_param(
                current_name,
                ts.parameters.id if ts and ts.parameters.id > 0 else default_current,
            )
            lines.append(f"* {dev.role} reference current")
            lines.append(f"{source_name} vdd {gate} DC {self._fmt_si(float(iref), 'A')}")
            handled_ports.add(gate)

        params = getattr(self.state, "global_parameters", {}) or {}
        if not handled_ports and float(params.get("tail_current_mirror_bias", 0.0) or 0.0) > 0.5:
            for dev in self.state.topology.devices:
                if dev.role != "tail_current_source" or dev.type != "nmos":
                    continue
                gate = dev.connections.get("gate", "")
                source = dev.connections.get("source", "0")
                body = dev.connections.get("body", source)
                if not gate:
                    continue
                ts = self.state.transistors.get(dev.id)
                iref = self._get_global_param(
                    "I_tail",
                    ts.parameters.id if ts and ts.parameters.id > 0 else 10e-6,
                )
                model = dev.model or self._proc.nmos_model or "nmos"
                lines.append("* Diode-connected NMOS mirror for tail bias")
                lines.append(f"Iref_tail vdd {gate} DC {self._fmt_si(float(iref), 'A')}")
                layout = realize_transistor_layout(self.state, dev.id)
                lines.append(self._mos_instance_line(f"BIAS{dev.id}", gate, gate, source, body, model, layout))
                handled_ports.add(gate)
                break

        for port in self.state.topology.ports:
            if port.direction != "bias":
                continue
            if port.id in handled_ports:
                continue
            vbias_v = self._get_explicit_bias_voltage(port.id)
            if vbias_v is None:
                vbias_v = fallback
                for dev in self.state.topology.devices:
                    if dev.connections.get("gate") != port.id:
                        continue
                    ts = self.state.transistors.get(dev.id)
                    if ts and ts.parameters.vgs > 0:
                        if dev.type == "pmos":
                            vbias_v = vdd - ts.parameters.vgs
                        else:
                            vbias_v = ts.parameters.vgs
                    break
            lines.append(f"V{port.id} {port.id} 0 DC {vbias_v:.4f}")

        if len(lines) == 1:
            return []
        lines.append("")
        return lines

    def _gen_stimuli(self) -> List[str]:
        vdd = self.state.simulation.supply.get("vdd", 1.2)
        vcm = vdd * 0.5
        inputs = [p for p in self.state.topology.ports if p.direction == "input"]
        lines = ["* -- Stimuli --"]
        if len(inputs) >= 2:
            if self._is_comparator():
                diff = float(self._get_global_param("input_step", 10e-3) or 10e-3)
                lines.append(f"* Common-mode = {vcm:.2f}V, differential input = {diff:.6g}V")
                lines.append(f"Vinp {inputs[0].id} 0 DC {vcm + 0.5 * diff:.6g} AC 0.5")
                lines.append(f"Vinn {inputs[1].id} 0 DC {vcm - 0.5 * diff:.6g} AC -0.5")
            else:
                lines.append(f"* Common-mode = {vcm:.2f}V, diff AC=0.5")
                lines.append(f"Vinp {inputs[0].id} 0 DC {vcm} AC 0.5")
                lines.append(f"Vinn {inputs[1].id} 0 DC {vcm} AC -0.5")
        elif len(inputs) == 1:
            lines.append(f"Vin {inputs[0].id} 0 DC {vcm} AC 1")
        if self._is_comparator():
            f_clk = float(self._get_global_param("f_clk", 100e6) or 100e6)
            period = 1.0 / max(f_clk, 1.0)
            tr = max(period * 0.01, 1e-12)
            tf = tr
            delay = period * 0.20
            high_time = period * 0.45
            gate_nets = {dev.connections.get("gate", "").lower() for dev in self.state.topology.devices}
            if "clk" in gate_nets:
                lines.append(f"Vclk clk 0 DC 0 PULSE(0 {vdd:.6g} {delay:.6g} {tr:.6g} {tf:.6g} {high_time:.6g} {period:.6g})")
            if "clkb" in gate_nets:
                lines.append(f"Vclkb clkb 0 DC {vdd:.6g} PULSE({vdd:.6g} 0 {delay:.6g} {tr:.6g} {tf:.6g} {high_time:.6g} {period:.6g})")
        lines.append("")
        return lines

    def _gen_load(self) -> List[str]:
        cl = self._get_global_param("CL", self.state.simulation.cload) if self._is_comparator() else self.state.simulation.cload
        if cl and cl > 0:
            outs = [p for p in self.state.topology.ports if p.direction == "output"]
            if outs:
                cl_ff = cl * 1e15
                lines = ["* -- Load --"]
                if self._is_comparator():
                    for idx, port in enumerate(outs):
                        name = "Cload" if idx == 0 else f"Cload_{port.id}"
                        lines.append(f"{name} {port.id} 0 {cl_ff:.1f}f")
                else:
                    lines.append(f"Cload {outs[0].id} 0 {cl_ff:.1f}f")
                lines.append("")
                return lines
        return []

    # Analyses

    def _gen_analyses(self) -> List[str]:
        lines = ["* -- Analyses --"]
        vcm = self.state.simulation.supply.get("vdd", 1.2) * 0.5
        lines.append(f".dc Vinp {vcm:.3f} {vcm:.3f} 0.001")
        sim = self.state.simulation
        if "ac" in sim.analyses:
            lines.append(f".ac dec {sim.ac_points} {sim.ac_start} {sim.ac_stop}")
        if self._needs_transient():
            tstep, tstop, tmax = self._transient_timing()
            lines.append(f".tran {tstep:.6g} {tstop:.6g} 0 {tmax:.6g}")
        lines.append("")
        return lines

    def _needs_transient(self) -> bool:
        if self._is_comparator():
            comparator_tran_targets = {
                "delay",
                "decision_time",
                "propagation_delay",
                "regeneration_time",
                "reset_time",
                "energy",
                "pdp",
            }
            if comparator_tran_targets & set(self.state.targets):
                return True
        if any(str(name).lower() in {"tran", "transient"} for name in self.state.simulation.analyses):
            return True
        if any(name in self.state.targets for name in ("slew_rate", "slew_rate_pos", "slew_rate_neg")):
            return True
        return any(ev.type in {"slew_rate", "slew_rate_pos", "slew_rate_neg"} for ev in self.state.evaluations)

    def _transient_timing(self) -> tuple[float, float, float]:
        if self._is_comparator():
            f_clk = float(self._get_global_param("f_clk", 100e6) or 100e6)
            period = 1.0 / max(f_clk, 1.0)
            tstop = 2.5 * period
            tstep = max(period / 2000.0, 1.0e-12)
            tmax = max(period / 4000.0, 1.0e-12)
            return tstep, tstop, tmax
        gbw_target = None
        for key in ("unity_gain_bandwidth", "ugbw"):
            target = self.state.targets.get(key)
            if target and target.min:
                gbw_target = float(target.min)
                break
        if gbw_target and gbw_target > 0:
            tstop = min(max(20.0 / gbw_target, 2.0e-8), 5.0e-6)
        else:
            tstop = 2.0e-7
        tstep = max(tstop / 4000.0, 1.0e-12)
        tmax = max(tstop / 8000.0, 1.0e-12)
        return tstep, tstop, tmax

    # Internal implementation note.

    def _gen_measures(self) -> List[str]:
        """AnalogRF-IR internal documentation."""
        lines = ["* -- Measures --"]

        # Internal implementation note.
        out = None
        for p in self.state.topology.ports:
            if p.direction == "output":
                out = p.id
                break
        if out is None:
            out = "vout"

        vdd = self.state.simulation.supply.get("vdd", 1.2)

        # Internal implementation note.
        ev_list = self.state.evaluations if self.state.evaluations else []

        if ev_list:
            for ev in ev_list:
                probe = ev.probe or out
                if ev.meas_formula:
                    # Internal implementation note.
                    lines.append(f".meas ac {ev.name} {ev.meas_formula}")
                elif ev.type == "ac_gain":
                    lines.append(f".meas ac {ev.name}_db max vdb({probe})")
                elif ev.type == "ugbw":
                    lines.append(f".meas ac {ev.name} when vdb({probe})=0")
                elif ev.type == "phase_margin":
                    lines.append(f".meas ac {ev.name} find vp({probe}) when vdb({probe})=0")
                elif ev.type == "dc_power":
                    lines.append(f".meas dc {ev.name} MAX par('{vdd}*abs(i(Vdd))')")
                elif ev.type in {"slew_rate", "slew_rate_pos", "slew_rate_neg"}:
                    lines.append(f"* .meas tran {ev.name}: computed from exported transient waveform in simulator")
                elif ev.type in {"delay", "decision_time", "propagation_delay", "regeneration_time", "reset_time"}:
                    lines.append(f"* .meas tran {ev.name}: computed from exported transient waveform in simulator")
                elif ev.type in {"energy", "energy_per_comparison", "pdp", "edp"}:
                    lines.append(f"* .meas tran {ev.name}: compact-model metric recorded by optimizer")
                elif ev.type in {"output_swing", "swing", "icmr", "icmr_min", "icmr_max"}:
                    lines.append(f"* .meas dc {ev.name}: computed from operating-point headroom in simulator")
                elif ev.type == "cmrr":
                    lines.append(f"* .meas ac {ev.name} ... ; CMRR measurement TBD (unsupported)")
                elif ev.type == "psrr":
                    lines.append(f"* .meas ac {ev.name} ... ; PSRR measurement TBD (unsupported)")
                elif ev.type == "operating_region":
                    lines.append(f"* {ev.name}: operating region check via print all")
                else:
                    lines.append(f"* .meas {ev.name}: unknown type '{ev.type}' - skipped")
        else:
            # Internal implementation note.
            targets = self.state.targets
            if "dc_gain" in targets:
                lines.append(f".meas ac dc_gain_db max vdb({out})")
            if "unity_gain_bandwidth" in targets:
                lines.append(f".meas ac ugbw when vdb({out})=0")
            if "phase_margin" in targets:
                lines.append(f".meas ac pm find vp({out}) when vdb({out})=0")
            if any(name in targets for name in ("slew_rate", "slew_rate_pos", "slew_rate_neg")):
                lines.append("* .meas tran slew_rate: computed from exported transient waveform in simulator")
            if self._is_comparator() and any(name in targets for name in ("delay", "decision_time", "propagation_delay", "regeneration_time", "reset_time")):
                lines.append("* .meas tran delay: computed from exported transient waveform in simulator")
            if any(name in targets for name in ("output_swing", "swing", "icmr", "icmr_min", "icmr_max")):
                lines.append("* .meas dc headroom metrics: output_swing and ICMR computed in simulator")
            if "power" in targets:
                lines.append(f".meas dc total_power MAX par('{vdd}*abs(i(Vdd))')")

        lines.append("")
        return lines

    # Save

    def save(self, path: str) -> str:
        content = self.generate()
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path


def generate_netlist(state: DesignState, output_path: Optional[str] = None) -> str:
    gen = NetlistGenerator(state)
    netlist = gen.generate()
    if output_path:
        gen.save(output_path)
    return netlist
